# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'selenium-webdriver', '~> 2.48.1'
gem 'rspec-expectations', '~> 3.3.1'
gem 'cucumber', '~> 3.1.0'